### PR TITLE
Add luacheck, update translations, replace ABMs, bug fixes

### LINKED ISSUE #45: The block signs:wooden_right_sign doesn't let a player walk through it, while signs:wooden_left_sign lets them.
Repro:

Place wooden signs in both directions and try to pass close. The sign pointing right lets you not pass as close as the sign pointing left.

May be not limited to wooden sign.

For my reference 157

### LINKED ISSUE #47: black or green board in itemframe is shown BEHIND that itemframe, instead of in front.
Not sure whether display modpack problem or itemframe problem.

When a player adds a black or green board to an itemframe, they are shown BEHIND that itemframe, instead of in front.

image
image

I will open a similar issue on the itemframes, maybe you can take a look together?

https://notabug.org/TenPlus1/itemframes/issues/3

For my reference 1273

### LINKED ISSUE #48: Placing direction sign against specific nodes crashes server
Placing e.g.
White direction sign (signs_road:white_right_sign)
against e.g. the top part of
White Truss Superstructure Simple Left End (bridger:truss_superstructure_simple_end_left_white)
causes the server to crash.

Error Message:
ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'signs_road' in callback item_OnPlace(): /data/world//worldmods/display_modpack/signs_api/init.lua:131: attempt to compare number with nil
stack traceback: /data/world//worldmods/display_modpack/signs_api/init.lua:131: in function </data/world//worldmods/display_modpack/signs_api/init.lua:91>

Another problematic nodes to place direction signs against:
Spiral Staircase (homedecor:spiral_staircase) - Some of the very upper parts, probably direction dependent
as well as several other rotated large superstructure nodes.

### LINKED ISSUE #51: punching a blackboard/greenboard changes the formspec
after placing: 
image

if you then punch the board, and right-click again:
image

note that in the 2nd form, the "font" button doesn't do anything.

### PR DESCRIPTION
**Pull request by Niklp09**
copied from https://github.com/pyrollo/display_modpack/pull/53

- Replaced `ontime_clocks` ABMs w/ nodetimers
- Removed intllib support + po files [and .po tools]
- Removed 0.4 compatibility code
- Added mt 5 tranlation support + new templates
- Added German translation
- Added translation support to font formspec
- Added luacheck + fixed luacheck warnings
- Fixed https://github.com/pyrollo/display_modpack/issues/51
- Fixed https://github.com/pyrollo/display_modpack/issues/48
- Fixed https://github.com/pyrollo/display_modpack/issues/45
- Fixed https://github.com/pyrollo/display_modpack/issues/47 (Note: needs a very up to-date itemframes version https://notabug.org/TenPlus1/itemframes/commit/9f17f744d75a6c70f84308f66cc8c0837b550dd1)
- Fixed some other nil crashes
- Fixed digital clocks nodeboxes and textures

### CODE REVIEW

File: .luacheckrc [hunk 1]
```diff
@@ -0,0 +1,26 @@
+unused_args = false
+
+ignore = {
+    "431", -- Shadowing an upvalue
+	"432", -- Shadowing an upvalue argument
+    "631", -- Line is too long
+}
```
Comment (wsor4035) [inline .luacheckrc]: really should be resolving issues, rather than ignoring them

**Review by wsor4035 — COMMENTED** [review]
single thought. probably should test the code with the amount of changes

File: .luacheckrc [hunk 2]
```diff
@@ -0,0 +1,20 @@
+unused_args = false
+
+read_globals = {
+	"minetest",
+	"string",
```
Comment (OgelGames) [inline .luacheckrc]:
```suggestion
```

File: boards/font_tinycurs.lua [hunk 3]
```diff
@@ -19,7 +19,8 @@ font_api.register_font('tinycurs',
 		marginbottom = -2,
 		linespacing = -4,
 		height = 19,
-		widths = { 
+		widths = {
+			-- luacheck: ignore
 			[0]=9, [32]=9, [33]=6, [34]=7, [35]=10, [36]=14, [37]=14, [38]=12, [39]=3, [40]=6, [41]=6, [42]=9, [43]=8, [44]=3, [45]=7, [46]=3, [47]=9, [48]=9, [49]=7, [50]=10, [51]=9, [52]=9, [53]=10, [54]=10, [55]=9, [56]=10, [57]=8, [58]=5, [59]=5, [60]=8, [61]=8, [62]=8, [63]=8, [64]=12, [65]=9, [66]=7, [67]=9, [68]=10, [69]=8, [70]=8, [71]=8, [72]=10, [73]=7, [74]=8, [75]=9, [76]=9, [77]=12, [78]=10, [79]=9, [80]=9, [81]=9, [82]=11, [83]=11, [84]=8, [85]=11, [86]=11, [87]=12, [88]=12, [89]=11, [90]=11, [91]=8, [92]=5, [93]=8, [94]=8, [95]=8, [96]=5, [97]=6, [98]=6, [99]=6, [100]=7, [101]=6, [102]=5, [103]=6, [104]=6, [105]=4, [106]=5, [107]=7, [108]=5, [109]=9, [110]=8, [111]=6, [112]=9, [113]=8, [114]=7, [115]=7, [116]=6, [117]=8, [118]=8, [119]=11, [120]=10, [121]=8, [122]=8, [123]=8, [124]=6, [125]=9, [126]=10, [8216]=4, [8217]=4, [8220]=6, [8221]=6
 		},
```
Comment (OgelGames) [inline boards/font_tinycurs.lua]:
```suggestion
		widths = {
			[  0]=9,  [ 32]=9,  [ 33]=6,  [ 34]=7,  [ 35]=10, [ 36]=14, [ 37]=14, [ 38]=12, [ 39]=3,  [ 40]=6,
			[ 41]=6,  [ 42]=9,  [ 43]=8,  [ 44]=3,  [ 45]=7,  [ 46]=3,  [ 47]=9,  [ 48]=9,  [ 49]=7,  [ 50]=10,
			[ 51]=9,  [ 52]=9,  [ 53]=10, [ 54]=10, [ 55]=9,  [ 56]=10, [ 57]=8,  [ 58]=5,  [ 59]=5,  [ 60]=8,
			[ 61]=8,  [ 62]=8,  [ 63]=8,  [ 64]=12, [ 65]=9,  [ 66]=7,  [ 67]=9,  [ 68]=10, [ 69]=8,  [ 70]=8,
			[ 71]=8,  [ 72]=10, [ 73]=7,  [ 74]=8,  [ 75]=9,  [ 76]=9,  [ 77]=12, [ 78]=10, [ 79]=9,  [ 80]=9,
			[ 81]=9,  [ 82]=11, [ 83]=11, [ 84]=8,  [ 85]=11, [ 86]=11, [ 87]=12, [ 88]=12, [ 89]=11, [ 90]=11,
			[ 91]=8,  [ 92]=5,  [ 93]=8,  [ 94]=8,  [ 95]=8,  [ 96]=5,  [ 97]=6,  [ 98]=6,  [ 99]=6,  [100]=7,
			[101]=6,  [102]=5,  [103]=6,  [104]=6,  [105]=4,  [106]=5,  [107]=7,  [108]=5,  [109]=9,  [110]=8,
			[111]=6,  [112]=9,  [113]=8,  [114]=7,  [115]=7,  [116]=6,  [117]=8,  [118]=8,  [119]=11, [120]=10,
			[121]=8,  [122]=8,  [123]=8,  [124]=6,  [125]=9,  [126]=10, [8216]=4, [8217]=4, [8220]=6, [8221]=6
		},
```

File: font_api/fallbacks.lua [hunk 4]
```diff
@@ -19,6 +19,7 @@
 -- This is the unicode char fallback map. If a char is not present in
 -- font, this maps indicates which char to try to use instead next.
 
+-- luacheck: ignore
```
Comment (OgelGames) [inline font_api/fallbacks.lua]: This can be fixed by removing the duplicate `à` on line 56.

File: font_api/registry.lua [hunk 5]
```diff
@@ -60,6 +60,7 @@ local function get_default_font()
 
 		-- If failed, chose first font
 		if default_font == nil then
+			-- luacheck: ignore 512
 			for _, font in pairs(font_api.registered_fonts) do
 				default_font = font
 				break
```
Comment (OgelGames) [inline font_api/registry.lua]: This loop should be replaced with:
```lua
default_font = next(font_api.registered_fonts)
```
Also the comment is wrong, this will choose whichever font happens to get picked first.

File: font_metro/init.lua [hunk 6]
```diff
@@ -18,6 +18,7 @@ font_api.register_font(
...
 	  }
 );
```
Comment (OgelGames) [inline font_metro/init.lua]:
```suggestion
		widths = {
			[  0]=10, [ 32]=10, [ 33]=4,  [ 34]=7,  [ 35]=12, [ 36]=10, [ 37]=14, [ 38]=13, [ 39]=4,  [ 40]=6,
			[ 41]=6,  [ 42]=10, [ 43]=8,  [ 44]=4,  [ 45]=7,  [ 46]=4,  [ 47]=10, [ 48]=10, [ 49]=7,  [ 50]=10,
			[ 51]=10, [ 52]=10, [ 53]=10, [ 54]=10, [ 55]=10, [ 56]=10, [ 57]=10, [ 58]=4,  [ 59]=4,  [ 60]=10,
			[ 61]=9,  [ 62]=10, [ 63]=10, [ 64]=16, [ 65]=14, [ 66]=10, [ 67]=13, [ 68]=11, [ 69]=9,  [ 70]=9,
			[ 71]=13, [ 72]=11, [ 73]=4,  [ 74]=9,  [ 75]=12, [ 76]=9,  [ 77]=17, [ 78]=11, [ 79]=14, [ 80]=10,
			[ 81]=15, [ 82]=12, [ 83]=10, [ 84]=12, [ 85]=10, [ 86]=14, [ 87]=17, [ 88]=12, [ 89]=12, [ 90]=10,
			[ 91]=6,  [ 92]=10, [ 93]=6,  [ 94]=9,  [ 95]=9,  [ 96]=6,  [ 97]=9,  [ 98]=10, [ 99]=9,  [100]=10,
			[101]=10, [102]=7,  [103]=9,  [104]=10, [105]=4,  [106]=5,  [107]=10, [108]=5,  [109]=14, [110]=10,
			[111]=10, [112]=10, [113]=10, [114]=8,  [115]=8,  [116]=7,  [117]=10, [118]=9,  [119]=15, [120]=9,
			[121]=9,  [122]=8,  [123]=7,  [124]=4,  [125]=7,  [126]=12, [160]=6,  [161]=4,  [162]=10, [163]=10,
			[164]=14, [165]=12, [166]=4,  [167]=8,  [168]=8,  [169]=16, [170]=9,  [171]=11, [172]=10, [173]=6,
			[174]=16, [175]=8,  [176]=8,  [177]=8,  [178]=9,  [179]=9,  [180]=6,  [181]=10, [182]=9,  [183]=4,
			[184]=7,  [185]=7,  [186]=10, [187]=11, [188]=14, [189]=14, [190]=14, [191]=10, [192]=12, [193]=12,
			[194]=12, [195]=12, [196]=14, [197]=12, [198]=16, [199]=13, [200]=9,  [201]=9,  [202]=9,  [203]=9,
			[204]=5,  [205]=5,  [206]=6,  [207]=8,  [208]=12, [209]=11, [210]=12, [211]=12, [212]=12, [213]=12,
			[214]=14, [215]=10, [216]=14, [217]=10, [218]=10, [219]=10, [220]=10, [221]=12, [222]=9,  [223]=10,
			[224]=9,  [225]=9,  [226]=9,  [227]=9,  [228]=9,  [229]=9,  [230]=15, [231]=9,  [232]=10, [233]=10,
			[234]=10, [235]=10, [236]=4,  [237]=4,  [238]=4,  [239]=5,  [240]=10, [241]=10, [242]=10, [243]=10,
			[244]=10, [245]=10, [246]=10, [247]=10, [248]=10, [249]=10, [250]=10, [251]=10, [252]=10, [253]=9,
			[254]=10, [255]=9,  [256]=12, [257]=9,  [258]=12, [259]=9,  [260]=14, [261]=9,  [262]=11, [263]=9,
			[264]=11, [265]=9,  [266]=11, [267]=9,  [268]=11, [269]=9,  [270]=10, [271]=13, [272]=12, [273]=10,
			[274]=9,  [275]=10, [276]=9,  [277]=10, [278]=9,  [279]=10, [280]=9,  [281]=10, [282]=9,  [283]=10,
			[284]=11, [285]=9,  [286]=11, [287]=9,  [288]=11, [289]=9,  [290]=13, [291]=9,  [292]=11, [293]=10,
			[294]=13, [295]=11, [296]=8,  [297]=5,  [298]=6,  [299]=4,  [300]=8,  [301]=5,  [302]=4,  [303]=4,
			[304]=4,  [305]=4,  [306]=12, [307]=8,  [308]=10, [309]=5,  [310]=12, [311]=10, [312]=10, [313]=9,
			[314]=6,  [315]=9,  [316]=5,  [317]=9,  [318]=7,  [319]=9,  [320]=7,  [321]=10, [322]=7,  [323]=11,
			[324]=10, [325]=11, [326]=10, [327]=11, [328]=10, [329]=12, [330]=11, [331]=10, [332]=12, [333]=10,
			[334]=12, [335]=10, [336]=12, [337]=10, [338]=18, [339]=16, [340]=11, [341]=8,  [342]=12, [343]=8,
			[344]=11, [345]=8,  [346]=10, [347]=8,  [348]=10, [349]=8,  [350]=10, [351]=8,  [352]=10, [353]=8,
			[354]=12, [355]=7,  [356]=12, [357]=9,  [358]=12, [359]=7,  [360]=10, [361]=10, [362]=10, [363]=10,
			[364]=10, [365]=10, [366]=10, [367]=10, [368]=10, [369]=10, [370]=10, [371]=10, [372]=15, [373]=15,
			[374]=12, [375]=9,  [376]=12, [377]=10, [378]=8,  [379]=10, [380]=8,  [381]=10, [382]=8,  [383]=5,
			[894]=4,  [913]=14, [914]=10, [915]=9,  [916]=14, [917]=9,  [918]=10, [919]=11, [920]=14, [921]=4,
			[922]=12, [923]=14, [924]=17, [925]=11, [926]=10, [927]=14, [928]=11, [929]=10, [931]=10, [932]=12,
			[933]=12, [934]=12, [935]=12, [936]=12, [937]=14, [945]=10, [946]=10, [947]=9,  [948]=10, [949]=9, 
			[950]=9,  [951]=10, [952]=10, [953]=5,  [954]=10, [955]=9,  [956]=10, [957]=9,  [958]=9,  [959]=10,
			[960]=11, [961]=10, [962]=9,  [963]=10, [964]=10, [965]=10, [966]=12, [967]=9,  [968]=12, [969]=12,
			[1026]=14,[1028]=13,[1033]=17,[1034]=17,[1035]=14,[1037]=11,[1039]=11,[1040]=14,[1041]=10,[1042]=10,
			[1043]=10,[1044]=12,[1045]=9, [1046]=18,[1047]=10,[1048]=11,[1049]=11,[1050]=12,[1051]=11,[1052]=17,
			[1053]=11,[1054]=14,[1055]=11,[1056]=10,[1057]=13,[1058]=12,[1059]=12,[1060]=12,[1061]=12,[1062]=12,
			[1063]=10,[1064]=16,[1065]=17,[1066]=13,[1067]=13,[1068]=10,[1069]=13,[1070]=17,[1071]=12,[1072]=9, 
			[1073]=10,[1074]=9, [1075]=8, [1076]=11,[1077]=10,[1078]=16,[1079]=9, [1080]=11,[1081]=11,[1082]=10,
			[1083]=10,[1084]=13,[1085]=10,[1086]=10,[1087]=10,[1088]=10,[1089]=9, [1090]=10,[1091]=9, [1092]=16,
			[1093]=9, [1094]=10,[1095]=9, [1096]=14,[1097]=15,[1098]=11,[1099]=12,[1100]=9, [1101]=10,[1102]=13,
			[1103]=11,[8216]=4, [8217]=4, [8220]=7, [8221]=7, [8364]=15
		},
	}
);
```

Comment (Niklp09) [reply font_metro/init.lua]: fonts are created w/ a script to read the diff easier i think this is a bad idea

Comment (OgelGames) [reply font_metro/init.lua]: Oh, that's true... Then maybe add a comment about that. (and in the other file)

**Review by OgelGames — APPROVED** [review]
